### ISSUE TITLE
+ (void)closeModal won't work when AppDelegate is using navigationController

### ISSUE THREAD

**Issue by maxhanzo** [arashpayan/appirater#110]
Hi, 
My app uses Navigation Controller, and closeModal couldn't close the AppStore view because it couldn't find the topMostViewController . 

I fixed this issue by not using closeModal, but instead doing the following, at Appirater.m  - 

-(void)productViewControllerDidFinish:(SKStoreProductViewController *)viewController {
    MyDelegate *appDelegate = [[UIApplication sharedApplication] delegate];
    [appDelegate.navigationController.topViewController dismissModalViewControllerAnimated:_usesAnimation];
}

This is not a good way to solve this issue, as this is a very specific way to deal with it. Unfortunately, I'm running out of time to release my app and will leave the code in this way, but I'm aware that this issue should be solved inside topMostViewController .

Thanks!

**Comment by arashpayan** [comment]
StoreKit will be removed in the next version of Appirater, so this should no longer be a problem.
