### ISSUE TITLE
MESSAGE_TITLE and RATE_BUTTON refer to the same localized string.

### ISSUE THREAD

**Issue by AndrewRoz** [arashpayan/appirater#153]
Since APPIRATER_LOCALIZED_MESSAGE_TITLE and APPIRATER_LOCALIZED_RATE_BUTTON both refer to the same key ("Rate %@") in the strings file, you can't set separate text for these without editing the class. There may be some cases where you prefer to have the title and rate button differ.

**Comment by arashpayan** [comment]
Sorry, this is outside of the scope of what I want for Appirater.
