### ISSUE TITLE
Localized dialog box not appearing 

### ISSUE THREAD

**Issue by thisisjeffwong** [arashpayan/appirater#172]
Hi, I just integrated Appirater with Cocoapods but the localized version of the dialog box does not appear when I have my device's language set to Chinese or Italian (that is what I tested).

Is there something we need to do to make sure the localized versions are used?  

I see the localizations being copied into the Appirater.bundle in the build log.

When we integrated this before Cocoapods, my coworker had to modify the .h file to use his own version of NSLocalizedString.

**Comment by romk1n** [comment]
i have the same problem installed via cocoapods but no translation appear, any help?

**Comment by manuelescrig** [comment]
Still same problem here.

**Comment by arashpayan** [comment]
Unable to reproduce

**Comment by ericjsalazar** [comment]
A little late here, but has anyone found a solution to this?

**Comment by liruqi** [comment]
Same here, does not work with Swift projects. 
Simple & ugly solution:
Copy *.lproj to main bundle, import, and 
`Appirater.setAlwaysUseMainBundle(true)`
