### ISSUE TITLE
templateReviewURLiOS7 is wrong

### ISSUE THREAD

**Issue by Poordeveloper** [arashpayan/appirater#182]
it goes to details page rather than review page, below one works for me.

@"itms-apps://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=APP_ID&onlyLatestVersion=true&pageNumber=0&sortOrdering=1&type=Purple+Software"

**Comment by JamesMcMahon** [comment]
Sorry, I know this issue is really old at this point but what is the point of `&type=Purple+Software` in the url?

Is that something that can be cut?
