### ISSUE TITLE
App Name Always Display Null

### ISSUE THREAD

**Issue by afiq90** [arashpayan/appirater#202]
I'm wondering why I always get the App name NULL even my code is correct in AppDelegate.m. Below is my error image and my code in AppDelegate.m. 

![appirater error](https://cloud.githubusercontent.com/assets/8640517/5602139/247766b0-9374-11e4-9cb8-8c32a8e2c3b2.png)

  [Appirater setAppId:@"552035781"];
    [Appirater setDaysUntilPrompt:2];
    [Appirater setUsesUntilPrompt:3];
    [Appirater setSignificantEventsUntilPrompt:-1];
    [Appirater setTimeBeforeReminding:2];
    [Appirater setDebug:YES];
    [Appirater appLaunched:YES];

**Comment by baljeetSingh21** [comment]
![screen shot 2015-01-07 at 10 00 38 am](https://cloud.githubusercontent.com/assets/4937916/5640953/1c3cc476-9654-11e4-8271-438728d225d1.png)
Add Bundle display Name in your plist file

**Comment by arashpayan** [comment]
Thanks @baljeetSingh21
