### ISSUE TITLE
iOS 8.1 - NSInternalInconsistencyException: Only run on the main thread!

### ISSUE THREAD

**Issue by kelvinjm** [arashpayan/appirater#207]
When <code>[Appirater appEnteredForeground:YES];</code> is used in AppDelegate <code>(void)applicationWillEnterForeground:(UIApplication *)application</code> and an application contains <b>UITextView</b> and the UITextView contains a <b>text</b> = application crash:

<i>*** Assertion failure in void _UIPerformResizeOfTextViewForTextContainer(NSLayoutManager *, UIView<NSTextContainerView> *, NSTextContainer *, NSUInteger)(), /SourceCache/UIFoundation/UIFoundation-371.4/UIFoundation/TextSystem/NSLayoutManager_Private.m:1547
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only run on the main thread!'</i>

Is really necessary to use:
<b>dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0)</b>
in <code>(void)appEnteredForeground:(BOOL)canPromptForRating</code>,  <code>(void)appLaunched:(BOOL)canPromptForRating</code> and <code>(void)userDidSignificantEvent:(BOOL)canPromptForRating</code> ?

**Comment by arashpayan** [comment]
The thread that Appirater works on has no bearing on what thread your other code will get executed on.
