### ISSUE TITLE
UIAlertView rotates when view is locked in portrait mode in iOS8

### ISSUE THREAD

**Issue by klwatanabe** [arashpayan/appirater#208]
I am testing on an iPhone5 with iOS 8.1. My application supports both portrait and landscape views. However, the majority of my application is locked to portrait mode. The alert view is allowing rotation even though the current view is locked to portrait mode.

**Comment by arashpayan** [comment]
Just want to add, that I can reproduce this. And it's a legitimage bug. I just haven't had time to track it down and fix it.

**Comment by arashpayan** [comment]
Version 2.3.0 uses `UIAlertController` on iOS 8+, so this shouldn't be a problem anymore.
