### ISSUE TITLE
Rate (null), If you enjoy using (null)

### ISSUE THREAD

**Issue by iOSDevil** [arashpayan/appirater#209]
Hi,

With appirater 2.0.4 installed via cocopods, running on iOS 8.2

With CFBundleName in the app target set to $(PRODUCT_NAME) or hard coded to a string results in 'Rate (null)'

Please advise.

**Comment by arashpayan** [comment]
Appirater uses the CFBundleDisplayName. In the future, I'd like to make it a developer option to use the CFBundleName. If you want, you can just change every reference to CFBundleDisplayName in the Appirater code to CFBundleName.

**Comment by vijaytholpadi** [comment]
I don't see this change when I import Appirater through cocoapods. Have manually changed this commit in my code for now. Any guesses why?

**Comment by arashpayan** [comment]
I don't use CocoaPods, so I only update it when major stuff changes in Appirater. For the latest release, pull the code from master.

**Comment by vijaytholpadi** [comment]
Cool. Thanks a bunch for confirming this.



—
