### ISSUE TITLE
App name (Null) in iOS 8

### ISSUE THREAD

**Issue by joris416** [arashpayan/appirater#210]
Hi,

First of all thanks for providing this framework.

I have one issue when implementing it in my iOS 8 (Swift) app.
It does not display my app name, despite of having added the "Bundle Display Name" rule to the info.plist 

I have also tried to change the regular Bundle name rule to my app name, but that didn't work either.

Here's my info.plist:
![schermafbeelding 2015-04-01 om 11 37 24](https://cloud.githubusercontent.com/assets/3315888/6938421/9c07ccea-d863-11e4-8c4e-f34a2e381e51.png)

Any advice on how to solve this issue would be highly appreciated

**Comment by arashpayan** [comment]
The one thing that jumps out to me from that screen shot is that the .plist file is in your 'Tests' directory. Do you have a plist file for your main product/package?
