### ISSUE TITLE
Does not build after installing through Cocoa Pods

### ISSUE THREAD

**Issue by neilunadkat** [arashpayan/appirater#212]
I installed the Library through cocoapods. 
After that the project does not build. 
This is the error it shows
![screen shot 2015-04-29 at 6 47 47 pm](https://cloud.githubusercontent.com/assets/985551/7391672/69e90a1e-eea0-11e4-8dc4-bed0a6fd3a31.png)

It seems like some sort of an architecture issue.
Any points on how to fix it?

**Comment by arashpayan** [comment]
Can you try adding the files to your project manually? There's really no
reason for Appirater to cause such an error. That looks like an issue with
CocoaPods.

**Comment by neilunadkat** [comment]
Adding it manually worked..
Weird that it did not work with CocoaPods..
