### ISSUE TITLE
Cannot submit build for review (There is an error for 1 of your localizations.)

### ISSUE THREAD

**Issue by neilunadkat** [arashpayan/appirater#213]
I get this error when I try to submit the build for review.
![screen shot 2015-04-30 at 11 52 29 am](https://cloud.githubusercontent.com/assets/985551/7407531/2797cbfa-ef31-11e4-80b3-75644f78094f.png)

I am a slight noob when it comes to handling localizations. Would anyone know what could be wrong?
The app works fine when I run it on the phone.
I have manually added the Appirator files.

**Comment by arashpayan** [comment]
I can't see any details in there about the error. I suspect the error is not with Appirater, but with your app store description or metadata on itunesconnect.

**Comment by JohnnyH1012** [comment]
Hi- same issue. Did you ever figure this out?

**Comment by asturies75** [comment]
Hi, the same issue also in my case but no solution at the moment. I had this problem after changing the main language for the App in the iTunes Connect.

Did someone face the same issue before?
