### ISSUE TITLE
Cocoa pod is out of date

### ISSUE THREAD

**Issue by cbrulak** [arashpayan/appirater#214]
The cocoapod is out of date. So I forked this repo and published a new one: https://github.com/cbrulak/appirater_iOS8/

pod 'Appirater_iOS8' 

I'll be happy to remove all that once this cocoapod is updated.

**Comment by arashpayan** [comment]
I just tagged the latest code as 2.0.5 and pushed the cocoapod update, so all should be well now. My apologies for the delay.
