### ISSUE TITLE
Calling setDelegate after sharedInstance has been called does not retain delegate

### ISSUE THREAD

**Issue by obuseme** [arashpayan/appirater#215]
If `setDelegate` is called before `sharedInstance` is called internally, the delegate is not properly retained on Appirater.

For example, any of these methods call `sharedInstance`

```
+ (void) setCustomAlertTitle:(NSString *)title
+ (void) setCustomAlertMessage:(NSString *)message
+ (void) setCustomAlertCancelButtonTitle:(NSString *)cancelTitle
+ (void) setCustomAlertRateButtonTitle:(NSString *)rateTitle
+ (void) setCustomAlertRateLaterButtonTitle:(NSString *)rateLaterTitle
```

Thus this code will fail to properly retain the delegate

```
[Appirater setCustomAlertTitle:[NSString stringWithFormat:@"Please rate %@", [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"]]];
self.appiraterDelegate = [[AppiraterDelegate alloc] init];
[Appirater setDelegate:self.appiraterDelegate];
```

This code will work:

```
self.appiraterDelegate = [[AppiraterDelegate alloc] init];
[Appirater setDelegate:self.appiraterDelegate];
[Appirater setCustomAlertTitle:[NSString stringWithFormat:@"Please rate %@", [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"]]];
```

It looks like it's because how the `dispatchOnce` in `sharedInstance` sets the delegate on the shared instance.  I think (haven't tried it) if `setDelegate` is changed to this, it will work:

```
+ (void)setDelegate:(id<AppiraterDelegate>)delegate{
    [Appirater sharedInstance].delegate = delegate;
}
```

**Comment by arashpayan** [comment]
I see what you're saying. And it has been set up in a funky way. Also, the way the delegate is being used in the rest of the code isn't consistent (sometimes using the ivar directly instead of calling through the accessor). All the delegate stuff needs to be cleaned up. I don't have much time this week, but I'd happily accept a pull request. :-)

**Comment by obuseme** [comment]
Sure no problem.  Does that seem like a sound approach, using `sharedInstance` to reference the `delegate`?

**Comment by arashpayan** [comment]
Yeah, using the `sharedInstance` to access it everywhere is perfect.

**Comment by Blackjacx** [comment]
I have the same issue. Would appreciate a fix :-)

**Comment by ConfusedVorlon** [comment]
I'm not sure what your timing is on 3.0, but it would be good to get a quick fix on this one. It is a really annoying bug that just caused me quite a bit of wasted time.

It doesn't seem to be an API change - so no need for it to be 3.0 unless that is soon.

in swift - this doesn't work:

```
        Appirater.setAppId(ConfigurationManager.sharedManager.appId)

            Appirater.setOpenInAppStore(false)
            Appirater.setDaysUntilPrompt(1)
            Appirater.setUsesUntilPrompt(10)
            Appirater.setCustomAlertTitle("Loving the app?\nIf so then please leave us a review.")
              
            Appirater.setDelegate(self)

            Appirater.setDebug(true)
            Appirater.appLaunched(true)
```

```
        Appirater.setAppId(ConfigurationManager.sharedManager.appId)
  
            Appirater.setDelegate(self)

            Appirater.setOpenInAppStore(false)
            Appirater.setDaysUntilPrompt(1)
            Appirater.setUsesUntilPrompt(10)
            Appirater.setCustomAlertTitle("Loving the app?\nIf so then please leave us a review.")
            
            Appirater.setDebug(true)
            Appirater.appLaunched(true)
```
