### ISSUE TITLE
UIAlertView and UIActionSheet Deprecated in iOS 8

### ISSUE THREAD

**Issue by doctorc** [arashpayan/appirater#222]
Note that UIAlertView and UIActionSheet are deprecated in iOS 8.  Need to update app to UIAlertController for iOS 9.

**Comment by arashpayan** [comment]
Yes, that's true, but there are still a lot of people on iOS 7 devices, so we still need to use UIAlertView to support them.

**Comment by fulldecent** [comment]
The correct way to handle this situation is to use preprocessor commands to disable this based on the target API.
