### ISSUE TITLE
SKStoreProductViewController doesn't allow you to actually press the "Write a Review" button

### ISSUE THREAD

**Issue by burhanaksendir** [arashpayan/appirater#224]
in iOS 8 you cannot press the button to write a review if you use SKStoreProductViewController.

**Comment by markst** [comment]
this seems to be the case for me on iOS 9.2.1

**Comment by arashpayan** [comment]
Apple disabled writing reviews from `SKStoreProductViewController` back in iOS 6 or 7. That's why this is no longer the default in Appirater.
