### ISSUE TITLE
Number Keyboard pops in on pressing No thanks or Remind me later

### ISSUE THREAD

**Issue by vickyrappier** [arashpayan/appirater#227]
Hello Team,

I am using Appirator component in my app , my issue is when i press the no thanks or Remind me later button Number Keyboard pops in.

What can be the cause.

I am sure after removing this component it works fine in the current screen where the popup is not shown but as soon as I add pods I get this Error.

**Comment by arashpayan** [comment]
Do you have a `UITextField` somewhere in your UIView's hierarchy that has focus before Appirater shows up? Maybe focus is just returning to it after the UIAlertView gets dismissed.

**Comment by vickyrappier** [comment]
Yes I have a verification screen in which I enter the Number hence used the
number keypad. After the number is verified the Keyboard is resigned and
moved to another view controller.

This next view controller is where we see the Appirator alert and on press
nothanks or remind me later  shows the keyboard. We are not able to
understand how the becomes first responder event is triggered by Appritator
alert button action.



From:  Arash Payan <notifications@github.com>
Reply-To:  arashpayan/appirater
<reply+00a9e1ab0c5dd26a551dc80bc6fcf10874d3618eec594db992cf00000001122291bd9
2a169ce067becd9@reply.github.com>
Date:  Wednesday, 30 September 2015 1:51 am
To:  arashpayan/appirater <appirater@noreply.github.com>
Cc:  Vicky Dhas <vickydhas@rappier.com>
Subject:  Re: [appirater] Number Keyboard pops in on pressing No thanks or
Remind me later (#227)


Do you have a UITextField somewhere in your UIView's hierarchy that has
focus before Appirater shows up? Maybe focus is just returning to it after
the UIAlertView gets dismissed.


Reply to this email directly or view it on GitHub
<https://github.com/arashpayan/appirater/issues/227#issuecomment-144134574>
.

**Comment by arashpayan** [comment]
I'm not sure what's causing that behavior. The UIKit related functionality of Appirater is just a UIAlertView (and the StoreKit controller that nobody should be using). It sounds like there's something going on in your code after the UIAlertView gets dismissed.
