### ISSUE TITLE
Not displaying Appirater Alertview

### ISSUE THREAD

**Issue by royherma** [arashpayan/appirater#232]
My app is swift based 9.0, installed Appirater via cocoapods. Have this code in my AppDelegate:

```
    Appirater.setAppId("106037XXXX") //replace X's with last 4 digits just for here
    Appirater.setDaysUntilPrompt(2)
    Appirater.setUsesUntilPrompt(10)
    Appirater.setSignificantEventsUntilPrompt(-1)
    Appirater.setTimeBeforeReminding(2)
    Appirater.setDebug(true)
```

Code is definitely executed, but no popup appears. Tried both on simulator and actual device. Any ideas?

Thanks

**Comment by kontextbewusst** [comment]
Same here with an ObjC app... the alertview is not shown.

**Comment by benjamincombes** [comment]
Same thing for me, in Swift too.

**Comment by Clafou** [comment]
I guess this is because Appirater uses UIAlertView, which is deprecated in iOS9.

**Comment by royherma** [comment]
Deprecated doesn't mean it shouldn't work... @Clafou

**Comment by Clafou** [comment]
@royherma You're right, I stand corrected. I just did a quick test in an iOS9 project and UIAlertView, although deprecated, did work.

**Comment by jlubeck** [comment]
Same here! It´s been a few months now. No news about this?

**Comment by arashpayan** [comment]
You've set it to only show up after 2 days. Have you waited 2 days? If you want to test it right away, change `setDaysUntilPrompt` to 0.
