### ISSUE TITLE
UIAlertView Deprecated Starting in iOS 9.0

### ISSUE THREAD

**Issue by ctd-mh3** [arashpayan/appirater#247]
This class has been deprecated and appirater should be updated to use the recommended replacement.

https://developer.apple.com/reference/uikit/uialertview

**Comment by arashpayan** [comment]
Fixed in https://github.com/arashpayan/appirater/commit/b9a985f4906e97de5d39fd022eef3f8569b01c96

Available in release 2.3.0.
