### ISSUE TITLE
iOS 10.3 in-app review!

### ISSUE THREAD

**Issue by kohtenko** [arashpayan/appirater#250]
This is great opportunity for Appirater to show new native dialog instead of sending to AppStore devices driven by iOS 10.3 or higher.

https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewIniOS/Articles/iOS10_3.html

**Comment by yoasha** [comment]
I also think so. It will be great!

**Comment by arashpayan** [comment]
Great idea. Adding this to the 3.0 milestone.

**Comment by gapl** [comment]
What is the current status behind this? Is there any timeframe for version 3.0?

**Comment by arashpayan** [comment]
Sorry @gapl, no timeframe on this. I don't even do much iOS coding these days, so I'm not sure when I'll have a chance to work on this. If someone wants to send a pull request with this feature, I can merge it and push out an update to the 2.x series.

**Comment by Grumps87** [comment]
It seems that some pre-release article on 10.3 suggest that there's a limitation to requestReview(). One mentioned that regardless of your app version (even with multiple updates), it will not show more than 3 times a year. I'm not sure if this has changed.

What could be useful is the new URL parameter (action=write-review) that automatically open up "Write a Review" form. Simply have to append it to App Store URL. I'm still in the process of testing this for older version and if it works for 6.0/7.0, we no longer need to have multiple URLs for different OS version.

https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview

**Comment by arashpayan** [comment]
@iv-mexx contributed a pull request that integrates `SKStoreReviewController`. @Grumps87, there is still the problem of not getting feedback from the new review UI and the limitations about how often it lets you display it, but that's another problem I'll have to think about for awhile.
