### ISSUE TITLE
iOS 11 App Store Review Guidelines

### ISSUE THREAD

**Issue by zodester** [arashpayan/appirater#256]
The new app store review guidelines indicate that apps using Appirater (in its current form) will begin to be rejected.

> Use the provided API to prompt users to review your app; this functionality allows customers to provide an App Store rating and review without the inconvenience of leaving your app, and we will disallow custom review prompts.

Perhaps Appirater could continue to be leveraged as a throttling/triggering mechanism alongside the new SKStoreReviewController API?

**Comment by arashpayan** [comment]
That's an excellent idea. However, I simply don't have the time to work on Appirater anymore. If somebody can take over for me, that would be a great service to the entire community of users.

**Comment by arashpayan** [comment]
Version 2.2.0 uses the `SKStoreReviewController`, thanks to the efforts of @iv-mexx.
