### ISSUE TITLE
SKStoreReviewController is displayed everytime (even with DEBUG = FALSE)

### ISSUE THREAD

**Issue by Timenote** [arashpayan/appirater#259]
Hi, this is my parameters : 

[Appirater setAppId:@"XXXX"];
[Appirater setDaysUntilPrompt:1];
[Appirater setUsesUntilPrompt:5];
[Appirater setSignificantEventsUntilPrompt:-1];
[Appirater setTimeBeforeReminding:2];
[Appirater setDebug:NO];
        
[Appirater appLaunched:YES];

Problem is : SKStoreReviewController is displayed everytime i launch my app (downloaded from the appstore) while i hit the "later" button.

Thanks!

**Comment by spookyd** [comment]
I experienced the same issue and after digging around I have found that the `kAppiraterRatedCurrentVersion` does not get set in the UserDefaults if SKStoreReviewController is used. I don't think this is intended functionality. Might need to open a pull request with the placement switched around to start a work in progress discussion.

**Comment by arashpayan** [comment]
Version 2.3.0 now sets the value in `NSUserDefaults` even if `SKStoreReviewController` is used.
