### ISSUE TITLE
Appirater methodes delegate dont respond with SKStoreReviewController

### ISSUE THREAD

**Issue by MohamedSadokAbid** [arashpayan/appirater#262]
When using OS less than 10.3 everything is fine, but with SKStoreReviewController (OS 10.3 and more) Appirater methodes delegate dont respond (expect appiraterDidDisplayAlert). To resume:

- appiraterDidDisplayAlert works fine !
- appiraterDidOptToRate not tested.
- appiraterDidDeclineToRate dont work with SKStoreReviewController.
- appiraterDidOptToRemindLater dont work with SKStoreReviewController.

**Comment by arashpayan** [comment]
Sadly, this will have to be the way it goes with 10.3 and later, unless Apple provides some insight into how the user responds to the dialog. Using SKStoreReviewController is very much a fire and forget operation.
