### ISSUE TITLE
Using Xcode 8.2 :  Unexpected '@' in program

### ISSUE THREAD

**Issue by MangeshVyas** [arashpayan/appirater#267]
Getting below error with Pod 👍:     Unexpected '@' in program

**Comment by MangeshVyas** [comment]
Unexpected '@' in program when trying to use with PodFile 
and Xcode: 8.2

**Comment by arashpayan** [comment]
Fixed in #264

**Comment by arashpayan** [comment]
I just released a fix for this in 2.3.1.
