### ISSUE TITLE
iOS 11: App Store app shows that it cannot connect to app store

### ISSUE THREAD

**Issue by danleechina** [arashpayan/appirater#268]
In iOS 11, I found it should use iOS7-like way to jump to App Store. So please check it.

**Comment by arashpayan** [comment]
Appirater isn't involved in the actual display of the app store page. Sounds like a network problem.

**Comment by danleechina** [comment]
No, maybe my words are not clear. It's not a network problem. It's the url parameter passed by openURL method. I saw you have two URL. One is iOS 7 and earlier, the other is iOS 8 and later.  The problem is in iOS 11, I found we should pass iOS 7's URL(in your souce code name `templateReviewURLiOS7`) to openURL method.
