### ISSUE TITLE
Submit button grayed out

### ISSUE THREAD

**Issue by djcomy** [arashpayan/appirater#271]
Why Submit button is grayed out?

**Comment by arashpayan** [comment]
The submit button is disabled when the app is run via Xcode. Once it's in the store the button will be enabled once the controller appears.

**Comment by djcomy** [comment]
Great!  Thank You for a quick response! This was useful because I would try to fix this to the death :D! Btw, works like a charm...

**Comment by student-t** [comment]
Why would you do this to make debugging harder?
