### ISSUE TITLE
Is there a way to put Appirater into a Ruby on Rails web app, which is being rendered in chrome / safari on an iPhone?

### ISSUE THREAD

**Issue by JamesLivengood** [arashpayan/appirater#285]
I am trying to install a review popup, but because of Apple's new guidelines, I'm not sure if I am allowed to not use their SKStoreReviewController. 

Is there a way to use Appirater in a Ruby on Rails web app? It is in a React Native wrapper as well.

**Comment by arashpayan** [comment]
I really don't know. There is no out of the box solution that I've created this, but I'm sure you can write some bindings to it from React Native.
