### ISSUE TITLE
appirater causes defaults changed notfication from multiple threads

### ISSUE THREAD

**Issue by jum** [arashpayan/appirater#44]
Appirater uses dispatch_async to schedule work in the low priority global queue, this causes defaults changed events to be posted from multiple threads and assorted race conditions in naive apps. I would believe that this should be mentioned in the readme as it surprised me and causes some head scratching to find out where that crash came from.

**Comment by stsandro** [comment]
@jum, how exactly did you solve this problem? I recently released a new version of my app that I haven't updated in a while. I see a few crashes on -[Appirater incrementUseCount] especially on iOS 9 and 10. Haven't seen this on iOS 11. And it only occurs in the free app that has AdMob ads for monetization. I believe that AdMob and Appirater write/read to NSUserDefaults at  the same time and from different threads.

Can you give me a hint how to solve this crash?

**Comment by jum** [comment]
I have been packaging all my code using dispatch_async onto the main thread to avoid the concurrency problems. Rereading the docs about the defaults changed events this can happen anyways, so you have to synchronize your handlers. I had to update user interface, so moving it to the main thread was the easiest.
