### ISSUE TITLE
Allow for more buttons like an email us button

### ISSUE THREAD

**Issue by tkrones** [arashpayan/appirater#70]
One of the biggest complaints I have with apple's app store is that as a developer I can't respond to user's reviews.  It would be nice if appirater would give users an option to email the developer if they have complaints or suggestions.  I've does something similar in some of my apps with good success.  No bad reviews and useful feedback.

**Comment by arashpayan** [comment]
After further reflection, I think this is outside of the scope of Appirater. There are more sophisticated app review mechanisms that help you with this kind of thing (apptentive et al.).
