### ISSUE TITLE
APPIRATER_LOCALIZED_APP_NAME should use kCFBundleNameKey, not @"CFBundleDisplayName"

### ISSUE THREAD

**Issue by hiltonc** [arashpayan/appirater#89]
A recent commit "changed" this, but I don't think it was the right thing to do. In my app I use CFBundleName for the full name of the app, and CFBundleDisplayName for the name that appears under the app icon. I'd like Appirater to use the full name, not the short name. Perhaps I'm doing it wrong?

**Comment by GoldenJoe** [comment]
I know this is old, but add me to the list of people who agree. It's easy to forget to change this and end up with a bug in your first release.

**Comment by MinerP** [comment]
Agreed with this. I'm setting a manual title and message just to get passed this.
